---
label: Products
hide_body: false
fields:
- name: templateKey
  type: text
  config:
    required: false
  label: Template Key
  hidden: true
  default: product-post
- name: sortnumber
  type: number
  label: Sort number
  description: The order you'd like the products displayed on the page.
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
    required: true
- name: title
  type: text
  config:
    required: true
  label: Title
  description: Title of the product
- name: description
  type: textarea
  default: ''
  config:
    required: true
    wysiwyg: false
    schema:
      format: markdown
  label: Description
  description: A description of the product
- name: featuredimage
  type: file
  config:
    maxSize: 64
  label: Featured Image
  description: Bottle image with no background
- name: colorscheme
  type: select
  default: wheat
  config:
    required: true
    options:
    - wheat
    - storm
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Color Scheme
  description: Select the background color and wheat color for this product section
pages:
- mendocino-spirits-3.0/src/pages/products/captain-fletcher-s-private-reserve.md
- mendocino-spirits-3.0/src/pages/products/straight-bourbon-whiskey.md
